### ISSUE TITLE
Download "PEM bundle" Certificate

### ISSUE THREAD

**Issue by vlauciani** [ConsortiumGARR/tcs-garr#10]
Hello,

I'm using `tcs-garr` to request and download certificates, but I can't figure out whether it's possible to obtain the equivalent of the "PEM bundle" provided on the HARICA website (see attached screenshot).  

From what I see, the available options are only `fullchain` and `only-certificate`, but neither of them appears to return the "PEM bundle" as downloaded from the web interface.

Being able to download the PEM bundle would be very helpful to avoid the following error when using `openssl`:

```
$ openssl s_client -connect <host>:443 -showcerts
---
. . .
SSL handshake has read 2283 bytes and written 368 bytes
Verification error: unable to verify the first certificate
---
```

Instead of the expected output:
```
$ openssl s_client -connect <host>:443 -showcerts
---
SSL handshake has read 6250 bytes and written 404 bytes
Verification: OK
---
```
Thanks in advance!

<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/a975ec6d-cbed-4099-a8af-f713ab99ad2e" />

**Comment by rizlas** [comment]
Hi @vlauciani, what version of tcs-garr are you running?

**Comment by vlauciani** [comment]
The last one, `0.23.3`, by docker image

**Comment by pasqualemandato** [comment]
Hello,

The issue you're encountering was related to how the certificate chain was previously constructed by `tcs-garr`. In earlier versions, the chain would end at the **self-signed** certificate `CN=HARICA TLS RSA Root CA 2021`, which is **not included** in the truststore of some older systems. This could lead to errors such as:

```
Verification error: unable to verify the first certificate
```

As of version **0.23.3**, this behavior has been corrected. The certificate chain now ends with:

```
CN=HARICA TLS RSA Root CA 2021
signed by
CN=Hellenic Academic and Research Institutions RootCA 2015
```

This intermediate certificate (`RootCA 2015`) **is present** in the truststores of many older systems, which improves compatibility and resolves the `openssl s_client` verification issue.

The result you get from `tcs-garr` is equivalent to the **PEM bundle** provided by the HARICA web interface.

We also verified that the **Docker image** is aligned with this fix. If you're using the `latest` tag, we recommend either:

* explicitly pinning to the fixed version:
  `ghcr.io/consortiumgarr/tcs-garr:0.23.3`

* or forcing a fresh pull of the `latest` tag to ensure you're on the updated image:
  `docker pull ghcr.io/consortiumgarr/tcs-garr:latest`

Let us know if the issue persists after updating!

Best regards

**Comment by vlauciani** [comment]
Hello,

I'm using the Docker image with the specific tag `0.23.3` (not `latest`).

I tested it again, but something still doesn’t seem to work as expected. I’ll try to reproduce the issue more precisely.

Here’s the `head` and `tail` of the "PEM bundle" (`Cert_bundle.pem`) downloaded directly from the HARICA website:
```
subject=CN=webservices.ingv.it, O=Istituto Nazionale di Geofisica e Vulcanologia, L=Roma, C=IT  
issuer=CN=GEANT TLS RSA 1, O=Hellenic Academic and Research Institutions CA, C=GR  
-----BEGIN CERTIFICATE-----
MIIH7jCCBlagAwIBAgIQcy6V/8PtrS1yRs+jWXSDiTANBgkqhkiG9w0BAQsFADBgMQswCQYDVQQG
EwJHUjE3MDUGA1UECgwuSGVsbGVuaWMgQWNhZGVtaWMgYW5kIFJlc2VhcmNoIEluc3RpdHV0aW9u
cyBDQTEYMBYGA1UEAwwPR0VBTlQgVExTIFJTQSAxMB4XDTI1MDYxMzA3MjQxMFoXDTI2MDYxMzA3
MjQxMFowczELMAkGA1UEBhMCSVQxDTALBgNVBAcMBFJvbWExNzA1BgNVBAoMLklzdGl0dXRvIE5h
emlvbmFsZSBkaSBHZW9maXNpY2EgZSBWdWxjYW5vbG9naWExHDAaBgNVBAMME3dlYnNlcnZpY2Vz
LmluZ3YuaXQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC9xAGxSFCDyjKI2aTVhT3g
+9Fr/L+taYo0lOMp1FqNwPClMInzndJiaHu8ItwrK59+GdcTsfDPNGHDnDmg2lBOBMUbthrBc9Wd
...
NQAKoz2YQ+WyzrparKVilMG6p6mdWTKeLy6eQDRhFSu9DrMYr4TBYxIp2e5ZLQBk96xbG3wSepBC
kTDA0MA0NybzM0gF5nTa82BMCED8EQXliWWsgqUorXuk7msadosX793M42llmAcj1zJkADzlyzi4
gcPvIc4skfmz1OW9jxxwyaR/41VYzPVyw7m0rsL9n3v5PCFJ1zrldYayKq9gOdwOZInNJQgPU6im
XEFBZWdqdR+xdL7qHVMkdzBRoFqnYjr2bonw87Rxk7dAsdzmUUPJTIayzDTdtU78XkOl0FivJWBX
DQPiVB2Z5NdOVPUANDnADA5octuC3YTG2ncpG9aNKM4ggAyr3imdnz5UZdioYkecv2TVJHT2lXE5
PH/ifJs8p9+WFgyzFsW97BUF1nKsZiUWvlyPY9C9PKuhI4OMeTEA99YIRXYjXDSZq300ko5sXUVK
VG2osAR4Sr3wqS5hLGNBfym7FZwsQ+/ja+fenEALAbAiEMpI9h71lpMpIhdx7rdRznNeSOok/pVM
aqvBZ0IvAq+yXb7d8C+tAND0IcUxYyyJqkE789RJdcGZO9JMXv4inBFIEuMAMlGPxzcroEx+ehDX
yGR0asw7CooV2DCfiEJlIsKzLcPZew==
-----END CERTIFICATE-----
```

And here’s the `head` and `tail` of the "fullchain" file generated using the following command:
```
$ docker run --rm --name tcs-garr \
  -e HARICA_USERNAME=<user> \
  -e HARICA_PASSWORD=<password> \
  -e HARICA_TOTP_SEED="otpauth://totp/HARICA:xxxxx&issuer=HARICA&digits=6" \
  -e HARICA_OUTPUT_FOLDER=/opt/certificates \
  -v <path>:<path> \
  ghcr.io/consortiumgarr/tcs-garr:0.23.3 \
  --debug download --force --id bd418783-xxxx-xxxx-xxxx-f36a056be407 \
  --output-filename myhost
```

Output:
```
-----BEGIN CERTIFICATE-----
MIIH7jCCBlagAwIBAgIQcy6V/8PtrS1yRs+jWXSDiTANBgkqhkiG9w0BAQsFADBg
MQswCQYDVQQGEwJHUjE3MDUGA1UECgwuSGVsbGVuaWMgQWNhZGVtaWMgYW5kIFJl
c2VhcmNoIEluc3RpdHV0aW9ucyBDQTEYMBYGA1UEAwwPR0VBTlQgVExTIFJTQSAx
MB4XDTI1MDYxMzA3MjQxMFoXDTI2MDYxMzA3MjQxMFowczELMAkGA1UEBhMCSVQx
DTALBgNVBAcMBFJvbWExNzA1BgNVBAoMLklzdGl0dXRvIE5hemlvbmFsZSBkaSBH
ZW9maXNpY2EgZSBWdWxjYW5vbG9naWExHDAaBgNVBAMME3dlYnNlcnZpY2VzLmlu
Z3YuaXQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC9xAGxSFCDyjKI
2aTVhT3g+9Fr/L+taYo0lOMp1FqNwPClMInzndJiaHu8ItwrK59+GdcTsfDPNGHD
nDmg2lBOBMUbthrBc9WdGnyi/EaWd4LkwNjkA1jPma/kSwXOPdd+pm039qRWetSV
...
7msadosX793M42llmAcj1zJkADzlyzi4gcPvIc4skfmz1OW9jxxwyaR/41VYzPVy
w7m0rsL9n3v5PCFJ1zrldYayKq9gOdwOZInNJQgPU6imXEFBZWdqdR+xdL7qHVMk
dzBRoFqnYjr2bonw87Rxk7dAsdzmUUPJTIayzDTdtU78XkOl0FivJWBXDQPiVB2Z
5NdOVPUANDnADA5octuC3YTG2ncpG9aNKM4ggAyr3imdnz5UZdioYkecv2TVJHT2
lXE5PH/ifJs8p9+WFgyzFsW97BUF1nKsZiUWvlyPY9C9PKuhI4OMeTEA99YIRXYj
XDSZq300ko5sXUVKVG2osAR4Sr3wqS5hLGNBfym7FZwsQ+/ja+fenEALAbAiEMpI
9h71lpMpIhdx7rdRznNeSOok/pVMaqvBZ0IvAq+yXb7d8C+tAND0IcUxYyyJqkE7
89RJdcGZO9JMXv4inBFIEuMAMlGPxzcroEx+ehDXyGR0asw7CooV2DCfiEJlIsKz
LcPZew==
-----END CERTIFICATE-----
```

I tried comparing the certificates using `openssl` with:
```
openssl x509 -in cert1.pem -noout -text > cert1.txt
openssl x509 -in cert2.pem -noout -text > cert2.txt
diff cert1.txt cert2.txt
```

and:
```
openssl x509 -in cert1.pem -noout -fingerprint -sha256
openssl x509 -in cert2.pem -noout -fingerprint -sha256
```

and they appear to be identical (although I found out that `openssl` only compares the first certificate and not the entire chain).

It’s possible that I made a mistake somewhere in the process; feel free to reach out privately if you need more details: `valentino.lauciani[ at ]ingv.it`.

Thanks again for your support

**Comment by pasqualemandato** [comment]
Hi Valentino,

Thanks a lot for the detailed follow-up

To clarify a few points:

1. The file downloaded from `tcs-garr:0.23.3` is **functionally equivalent** to the **PEM bundle** provided by HARICA. The only differences are:

   * Line wrapping: `tcs-garr` wraps the PEM content differently (after 64 characters), which is entirely normal and does not affect the certificate.
   * Comment lines: HARICA adds `subject=` and `issuer=` headers above each certificate, which are **not part of the PEM format** and are omitted by `tcs-garr`.

2. To confirm that the bundle is truly identical, you can **extract each individual certificate** from the PEM bundle (i.e., each block between `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`) into separate files and then run:

   ```bash
   openssl x509 -in certN.pem -noout -fingerprint -sha256
   ```

   The SHA256 fingerprints should match exactly between the HARICA bundle and the one from `tcs-garr`.

Thanks again for your thorough testing and feedback!

Best regards,

**Comment by rizlas** [comment]
@vlauciani can we close this one?

**Comment by vlauciani** [comment]
Yes, sure! I’ll reopen it if needed!

Thank you for the support.
